# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "post/"
  weight = 20
  
[[main]]
  name = "Music Observatory"
  url = "https://music.dataobservatory.eu/"
  weight = 22
  
  
[[main]]
  name = "CCS Demo Observatory"
  url = "https://ccs.dataobservatory.eu/"
  weight = 23


[[main]]
  name = "Open Source"
  url = "#featured"
  weight = 40
  
[[main]]
  name = "Team"
  url = "team/"
  weight = 50
  
[[main]]
  name = "FAQ"
  url = "faq/"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
